swagger: "2.0"
definitions:
  image:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: 镜像ID
      name:
        type: string
        description: 镜像名称
      platform:
        type: string
        description: 操作系统发行版，[suse, debian, ubuntu, centos, windows-server]
      osVersion:
        type: string
        description: 操作系统版本号
      architecture:
        type: string
        description: 镜像架构 i386, x86_64
      systemDiskSizeGB:
        type: integer
        description: 镜像系统盘大小
      imageSource:
        type: string
        description: 镜像来源 jcloud：官方镜像 marketplace：镜像市场镜像 self：用户自己的镜像 shared：其他用户分享的镜像
      osType:
        type: string
        description: 镜像的操作系统类型，[windows, linux]
      status:
        type: string
        description: <a href="https://www.jdcloud.com/help/detail/3871/isCatalog/1">参考镜像状态</a>
      createTime:
        type: string
        format: date-time
        description: 创建时间
      sizeMB:
        type: integer
        description: 镜像本身大小
      desc:
        type: string
        description: 镜像描述
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: 系统盘配置
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: 打包镜像数据盘映射信息
      snapshotId:
        type: string
        description: 云硬盘做系统盘的快照id，创建云主机时，默认使用此快照创建系统盘
      rootDeviceType:
        type: string
        description: 镜像支持的系统盘类型。localDisk：支持本地盘系统盘。cloudDisk：支持云盘系统盘
      progress:
        type: string
        description: 镜像复制时的进度，单位为百分比，例如：80
