swagger: "2.0"
definitions:
  imageConstraint:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: 镜像ID
      imageInstanceTypeConstraint:
        description: 镜像实例规格限制
        $ref: "#/definitions/imageInstanceTypeConstraint"
  imageInstanceTypeConstraint:
    x-jdcloud-module: vm
    properties:
      constraintsType:
        description: 受限制的实例规格。excludes：排除指定的实例类型；includes：只包含指定的实例类型，暂不支持includes
        type: string
      instanceTypes:
        description: 实例规格列表
        type: array
        items:
          type: string
